---
# defaults file for picostack_app
# turn off/on debug deploy
# deploy_debug: yes
# other vars
app_domain: picostack.mysite.org
admin_email: admin@{{ app_domain }}
deploy_user: "{{ ansible_ssh_user }}"
deploy_home_folder: "{{ ansible_env.HOME }}"
picostack_state_folder: "{{ deploy_home_folder }}/.picostack"
picostack_db_folder: "/var/picostack/db/"
picostack_db_owner: "www-data"
picostack_db_group: "www-data"
deploy_app_dir: "{{ deploy_home_folder }}/picostack_app"
django_dir: /usr/local/lib/python2.7/dist-packages
django_wsgi_dir: "{{ django_dir }}/picostack"
picostack_djnago_user: pstk
picostack_djnago_password: pstk
